config/routes.rb
Rails.application.routes.draw do
  root 'agents#front'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'

  resources :users
  resources :home
  resources :accounts

  resources :agents do
    resources :homes do
      resources :addresses
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :home
end

app/models/agent.rb
class Agent < ActiveRecord::Base
	has_many :homes, dependent: :destroy
end

app/models/home.rb
class Home < ActiveRecord::Base
	belongs_to :agent
	has_one :address, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_uniqueness_of :email
  validates_presence_of :email, :password_digest
  has_secure_password
  has_one :account
  after_create :create_account

  def create_account
    Account.create(user_id: self.id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize
  def show
    @user = current_user
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :a_agent
  before_action :b_home
  before_action :c_address, only: [:show, :edit, :update, :destroy]


  def index
    @address = @home.address
  end

  def show
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.home = @home
    if @address.save
      redirect_to agent_home_addresses_path(@agent, @home, @address)
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to agent_home_addresses_path(@agent, @home, @address)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to agent_home_path(@agent, @home)
  end

  private
  def address_params
    params.require(:address).permit(:street, :city, :state, :zip)
  end

  def a_agent
    @agent = Agent.find(params[:agent_id])
  end

  def b_home
    @home = @agent.homes.find(params[:home_id])
  end

  def c_address
    @address = @home.address
  end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  # before_action :agent

  def index
    @agents = Agent.all
  end

  def show
    @agent = Agent.find(params[:id])
  end

  def edit
    @agent = Agent.find(params[:id])
  end

  def new
    @agent = Agent.new
  end

  def update
    if @agent.update(agent_params[:id])
      redirect_to
    else
      render :edit
    end
  end

  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      redirect_to agents_path
    else
      render :new
    end
  end


  private

    def agent_params
      params.require(:agent).permit(:name, :phone, :email)
    end

    # def agent
    #   @agent = Agent.find(params[:id])
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :agent
  before_action :home, only: [:show, :edit, :update, :destroy]

  def index
  	@homes = @agent.homes.all
  end

  def show
  	@home = Home.find(params[:id])
  end

  def edit
  end

  def update
  	if @home.update(home_params)
  		redirect_to agent_homes_path(@agent, @home)
  	else
  		render :edit
  	end
  end

  def new
    @home = Home.new
  end

  def create
  	@home = @agent.homes.new(home_params)
  	if @home.save
  		redirect_to agent_homes_path(@agent)
  	else
  		render :new
  	end
  end

  def destroy
  	@home.destroy
  	redirect_to agent_homes_path(@agent)
  end

  private
  	def home_params
  		params.require(:home).permit(:bed, :bath, :sqft, :price, :sold, :like)
  	end

  	def agent
  		@agent = Agent.find(params[:agent_id])
  	end

  	def home
  		@home = @agent.homes.find(params[:id])
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to account_path(current_user.account)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to account_path(current_user.account)
    else
     render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/show.html.erb
<%= link_to 'logout', logout_path %>

<h2>Welcome <%= @user.email %></h2>

<h2> Click <%= link_to 'HERE', agents_path %> for Agent listings.</h2>

app/views/addresses/_form.html.erb
<%= form_for [@agent, @home, @address] do |f| %>
  <%= f.label :street %>
  <%= f.text_field :street %>
  <br />
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br />
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br />
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <br />
  <%= f.submit %>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Address</h1>
<hr />
<br >
<%= render 'form' %>

app/views/addresses/index.html.erb
<h1>Address</h1>
<hr />
<br />

<% if @address %>
  <ul>
    <li>Street: <%= @address.street %> </li>
    <li>City: <%= @address.city %> </li>
    <li>State: <%= @address.state %> </li>
    <li>Zip: <%=@address.zip %> </li>
  </ul>
  <br />
  <%= link_to 'Edit', edit_agent_home_address_path(@agent, @home, @address)%>
  <br />
  <%= link_to 'Delete', agent_home_address_path(@agent, @home, @address), method: :delete %>

  <hr />
<% else %>
  <h3>No address for this home</h3>
  <br />
  <%= link_to 'Add Address', new_agent_home_address_path(@agent, @home) %>
<% end %>

<ul>
  <%=link_to 'Back to Front Page', agents_path %>
  <%= link_to 'Back to listings by this agent', agent_path(@agent)%>
  <%= link_to 'Back to this listing', agent_home_path(@agent, @home)%>

</ul>

app/views/addresses/new.html.erb
<h1>New Address</h1>
<hr />
<br />
<%= render 'form' %>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/agents/edit.html.erb
<h1>Edit Your Agent Name</h1>

<%= form_for @agent do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :phone %>
  <%= f.text_field :phone, required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, required: true %>

  <%= f.submit %>
<% end %>

app/views/agents/front.html.erb
<h2>Welcome to the Real Estate Page of wonder!<h2>

<%= link_to 'Signup', signup_path %>

<%= link_to 'Login', login_path %>

app/views/agents/index.html.erb
<h1>Welcome to Our Real Estate Agency</h1>
  <% @agents.each do |agent| %>
    <ul>    
      <li><%= link_to "#{agent.name}", agent_path(agent) %></li>
      
      <li><%= link_to 'Listings', agent_homes_path(agent) %></li>
    </ul>

    <% end %>
<br />
<%= link_to 'Create New Agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>Submit a New Agent</h1>
<%= form_for @agent do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :phone %>
  <%= f.text_field :phone, required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, required: true %>

  <%= f.submit %>
<% end %>

app/views/agents/show.html.erb
<h1><%= @agent.name %></h1>

<ul>
  <li><%= @agent.phone %></li>
  <li><%= @agent.email %></li>
</ul>
<%= link_to 'Back To All Agents', agents_path %>
<%= link_to 'Edit Agent', edit_agent_path(params[:id]) %>

app/views/homes/_form.html.erb
<%= form_for [@agent, @home] do |f| %>

	<%= f.label :bed, placeholder: '# of Beds' %>
	<%= f.text_field :bed, required: true %>
	<br />
	<%= f.label :bath, placeholder: '# of Bathrooms' %>
	<%= f.text_field :bath, required: true %>
	<br />
	<%= f.label :sqft, placeholder: 'Home Square Footage' %>
	<%= f.text_field :sqft, required: true %>
	<br />
	<%= f.label :price, placeholder: 'Home Price' %>
	<%= f.number_field :price, required: true %>
	<br />
	<%= f.check_box :sold %>
	<%= f.label :sold %>
	<br />
	<%= f.check_box :like %>
	<%= f.label :like %>
	<br />
	<%= f.submit %>

<% end %>

app/views/homes/edit.html.erb
<h1>Editing </h1>
<hr />

<%= render(partial: 'form') %>

app/views/homes/index.html.erb
<h1>Listings yo mofo</h1>
  <ul>
  <% @agent.homes.each do |home| %>
        
      <li><%= link_to 'Listing', agent_homes_path(home) %></li>
      
      <li><%= link_to 'Address', agent_home_addresses_path(@agent, home) %></li>
    </ul>

    <% end %>
<br />
<%= link_to 'Create New Listing', new_agent_home_path(@agent) %>

app/views/homes/new.html.erb
<h1>New Home</h1>
<hr />

<%= render(partial: 'form') %>

app/views/homes/show.html.erb
<h1>This page loads now <h1>
<hr />

<%= link_to 'Edit Home', edit_agent_home_path(@agent, @home) %>
<br />
 	
 	<label>Number of Bedrooms</label>
 	<h4> <%= @home.bed %> </h4>
 	<label>Number of Bathrooms</label>
 	<h4> <%= @home.bath %> </h4>
 	<label>Home many Square Feet does the Home have?</label>
 	<h4> <%= @home.sqft %> </h4>
 	<label>Home Price</label>
 	<h4> <%= @home.price %> </h4>
 	<label>Has the Home been Sold?</label>
 	<h4> <%= @home.sold %> </h4>
 	<label>Do you Like the Home?</label>
 	<h4> <%= @home.like %> </h4>
 	<br />

 	<label>Listing Agent</label>
 	<h5> <%= @agent.name %> </h4>
 	<label>Phone</label>
 	<h5> <%= @agent.phone %> </h5>
 	<label>Email</label>
 	<h5> <%= @agent.email %> </h5>
 	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstateRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_for :user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>